### ISSUE TITLE
How to read the .vtk files?

### ISSUE THREAD

**Issue by AbidHussain70** [LSC-UBA/OpenEP#3]
I installed the paraview software, but when I upload .vtk files I get nothing.
Can you share the steps to export and read the file correctly in Paraview software?

**Comment by emmanuellujan** [comment]
Hi! :) There are many ways to visualize vtk files generated by OpenEP using Paraview, this is a very powerful visualization tool and I highly recommend taking the time to master it (check out the figures of [our manuscript](https://www.nature.com/articles/s41598-020-79858-y)). Remember that you don't need to convert the vtk files to other formats, the files generated by OpenEP are compatible with Paraview.  Please watch the webinars in [this link](https://www.paraview.org/tutorials/) for more information about how to use this tool.
